version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Newman
          command: |
            curl -L https://npmjs.org/install.sh | sudo sh
            -g newman --prefix ~/.npm-global
      - run:
          name: Run API tests
          command: |
            newman run Automation_Exercise.postman_collection.json
