version: 23.1.2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r API Automation_Exercise.postman_collection.json
      - run:
          name: Run API tests
          command: pytest API Automation_Exercise.postman_collection.json
