<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find locations</name>
   <tag></tag>
   <elementGuidId>eb88d3fd-48ef-43e7-8ff1-e331d69d9582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='global-header']/div/header/div[2]/div/nav/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>322112ae-37e8-487a-bb56-df948c2321b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.service.nsw.gov.au/service-centre</value>
      <webElementGuid>f55f21cd-63fb-4978-ab82-7793c8dc42e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavLink__link-M-HSy9SYcc</value>
      <webElementGuid>6d522497-3dc5-4d3e-b6b6-d6967ccbbb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find locations</value>
      <webElementGuid>8b998a7e-2534-46e9-9352-b3d440e5ee66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;global-header&quot;)/div[1]/header[@class=&quot;GlobalHeader-0xZ4-w1g3x&quot;]/div[@class=&quot;GlobalHeader__main-ORzg9dkzx0&quot;]/div[@class=&quot;Container-f-hqve2slU GlobalHeader__mainContainer-jduh-JKthi&quot;]/nav[@class=&quot;MainNav-AYWEJogDLj&quot;]/ul[@class=&quot;MainNav__list-peZtddYtxn&quot;]/li[@class=&quot;NavLink__listItem-VYVwsaNaTG&quot;]/a[@class=&quot;NavLink__link-M-HSy9SYcc&quot;]</value>
      <webElementGuid>2726face-9490-4d76-bb63-02499007bca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='global-header']/div/header/div[2]/div/nav/ul/li[4]/a</value>
      <webElementGuid>9bb5b9a2-9737-4afe-887e-2378298f65e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find locations')]</value>
      <webElementGuid>803719de-42a7-48cb-b717-8870664e146e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[1]/following::a[1]</value>
      <webElementGuid>a5188c66-fe9a-47c3-9ded-99545356540a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse services'])[1]/following::a[2]</value>
      <webElementGuid>7fe1d71b-8918-49cd-902c-1936cafb29c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::a[1]</value>
      <webElementGuid>d62edd59-1b6b-4527-9e51-9d06e753e9eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse services'])[2]/preceding::a[2]</value>
      <webElementGuid>a1f7b105-b03a-4789-80e7-17eb46191600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find locations']/parent::*</value>
      <webElementGuid>03a8a493-5ff3-4657-a9ce-37f8bb330d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.service.nsw.gov.au/service-centre')]</value>
      <webElementGuid>14055e2a-0483-4526-b458-f0915e560517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>d33d4ee8-8016-420a-abb1-87100abd82bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.service.nsw.gov.au/service-centre' and (text() = 'Find locations' or . = 'Find locations')]</value>
      <webElementGuid>2d726f51-e6ba-4c63-97e5-1d0ef5415e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
