<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search by suburb, postcode or current location_button button--primary button--xxlarge</name>
   <tag></tag>
   <elementGuidId>b20886e4-ea65-4946-b920-0a0ccf37aa42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button.button--primary.button--xxlarge</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d73460e-7fa3-4160-bc68-5c9403558979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary button--xxlarge</value>
      <webElementGuid>c95c6ce4-c070-4f27-aa4e-10ed49d19204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3f40be1e-8f78-4176-8c08-b5e803e4eb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>e3891a1a-032f-4e60-ad4b-0e67e572daf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locator&quot;)/div[@class=&quot;locator&quot;]/form[@class=&quot;locator__search&quot;]/div[@class=&quot;suburb-suggest&quot;]/div[@class=&quot;form__input-group form--search-group&quot;]/div[@class=&quot;form__actions&quot;]/div[@class=&quot;form__actions&quot;]/button[@class=&quot;button button--primary button--xxlarge&quot;]</value>
      <webElementGuid>b30b0fab-b823-4dcc-ba2a-24f593c3f97f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>258f6eac-1ef5-4fe6-9110-aca76cc61e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='locator']/div/form/div/div/div[2]/div/button</value>
      <webElementGuid>9e1cfc3b-69c4-404d-8490-95b8f4e0f484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by suburb, postcode or current location'])[1]/following::button[2]</value>
      <webElementGuid>e2557e5b-f73b-4fa4-92d2-0ba8ba61763a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find a Service NSW location'])[1]/following::button[2]</value>
      <webElementGuid>14a15cb2-4939-4a21-8410-7e061cfd02e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by centre type'])[1]/preceding::button[1]</value>
      <webElementGuid>a602b008-554b-418c-9ba4-5ebfe4a2bf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::button[1]</value>
      <webElementGuid>ae372dd5-414f-4019-a22f-3e89012eb675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>f6b261ad-3912-4f49-9e8f-533639b52fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>043ceae1-67e1-4968-b902-490d0793d477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
